-- For each event, pivot out counts that occurred during it,
-- including same PAs across multiple events (I think), and
-- the count at which the event occurred. Sample cols:
-- occurred_1_strike
-- result_at_1_strike
-- occurred_0_1
-- result_at_0_1
-- occurrences_of_0_2 (due to fouls)
-- Indicate missing data with nulls
-- Worth making a macro to list out each count, each strikes, each balls, etc?
SELECT 1
