version: 2


models:
  - name: event_transition_values
    description: ""


    # config:
    #   contract:
    #     enforced: true

    # constraints:
    #   - type: primary_key
    #     columns: []

    columns:
      - name: event_key
        description: ""
        data_type: uinteger
      - name: run_expectancy_start_key
        description: ""
        data_type: varchar
      - name: run_expectancy_end_key
        description: ""
        data_type: varchar
      - name: win_expectancy_start_key
        description: ""
        data_type: varchar
      - name: win_expectancy_end_key
        description: ""
        data_type: varchar
      - name: season
        description: ""
        data_type: smallint
      - name: league
        description: ""
        data_type: varchar
      - name: game_type
        description: ""
        data_type: enum('allstargame', 'divisionseries', 'exhibition', 'leaguechampionshipseries',
          'otherchampionship', 'regularseason', 'tiebreakerplayoff', 'wildcardseries',
          'worldseries')
      - name: inning_start
        description: ""
        data_type: utinyint
      - name: frame_start
        description: ""
        data_type: enum('top', 'bottom')
      - name: truncated_home_margin_start
        description: ""
        data_type: tinyint
      - name: batting_side
        description: ""
        data_type: enum('home', 'away')
      - name: base_state_start
        description: ""
        data_type: utinyint
      - name: outs_start
        description: ""
        data_type: utinyint
      - name: inning_end
        description: ""
        data_type: utinyint
      - name: frame_end
        description: ""
        data_type: enum('top', 'bottom')
      - name: truncated_home_margin_end
        description: ""
        data_type: tinyint
      - name: base_state_end
        description: ""
        data_type: utinyint
      - name: outs_end
        description: ""
        data_type: utinyint
      - name: runs_on_play
        description: ""
        data_type: utinyint
      - name: game_end_flag
        description: ""
        data_type: boolean
      - name: expected_runs_change
        description: ""
        data_type: decimal(18,3)
      - name: expected_home_win_change
        description: ""
        data_type: decimal(14,3)
      - name: expected_batting_win_change
        description: ""
        data_type: decimal(14,3)
