{% macro event_level_offense_stats() %}
    {{ return([
        "plate_appearances",
        "at_bats",
        "hits",
        "singles",
        "doubles",
        "triples",
        "home_runs",
        "total_bases",
        "strikeouts",
        "walks",
        "intentional_walks",
        "hit_by_pitches",
        "sacrifice_hits",
        "sacrifice_flies",
        "reached_on_errors",
        "reached_on_interferences",
        "inside_the_park_home_runs",
        "ground_rule_doubles",
        "infield_hits",
        "on_base_opportunities",
        "on_base_successes",
        "runs_batted_in",
        "grounded_into_double_plays",
        "double_plays",
        "triple_plays",
        "batting_outs",
        "balls_in_play",
        "balls_batted",
        "trajectory_fly_ball",
        "trajectory_ground_ball",
        "trajectory_line_drive",
        "trajectory_pop_fly",
        "trajectory_unknown",
        "trajectory_known",
        "trajectory_broad_type_air_ball",
        "trajectory_broad_type_ground_ball",
        "trajectory_broad_type_unknown",
        "trajectory_broad_type_known",
        "bunts",
        "batted_distance_plate",
        "batted_distance_infield",
        "batted_distance_outfield",
        "batted_distance_unknown",
        "batted_distance_known",
        "fielded_by_battery",
        "fielded_by_infielder",
        "fielded_by_outfielder",
        "fielded_by_known",
        "fielded_by_unknown",
        "batted_angle_left",
        "batted_angle_right",
        "batted_angle_middle",
        "batted_angle_unknown",
        "batted_angle_known",
        "batted_location_plate",
        "batted_location_right_infield",
        "batted_location_middle_infield",
        "batted_location_left_infield",
        "batted_location_left_field",
        "batted_location_center_field",
        "batted_location_right_field",
        "batted_location_unknown",
        "batted_location_known",
        "batted_balls_pulled",
        "batted_balls_opposite_field",
        "runs",
        "times_reached_base",
        "times_lead_runner",
        "times_force_on_runner",
        "times_next_base_empty",
        "stolen_base_opportunities",
        "stolen_base_opportunities_second",
        "stolen_base_opportunities_third",
        "stolen_base_opportunities_home",
        "stolen_bases",
        "stolen_bases_second",
        "stolen_bases_third",
        "stolen_bases_home",
        "caught_stealing",
        "caught_stealing_second",
        "caught_stealing_third",
        "caught_stealing_home",
        "picked_off",
        "picked_off_first",
        "picked_off_second",
        "picked_off_third",
        "picked_off_caught_stealing",
        "outs_on_basepaths",
        "unforced_outs_on_basepaths",
        "outs_avoided_on_errors",
        "advances_on_wild_pitches",
        "advances_on_passed_balls",
        "advances_on_balks",
        "advances_on_unspecified_plays",
        "advances_on_defensive_indifference",
        "advances_on_errors",
        "plate_appearances_while_on_base",
        "balls_in_play_while_running",
        "balls_in_play_while_on_base",
        "batter_total_bases_while_running",
        "batter_total_bases_while_on_base",
        "extra_base_advance_attempts",
        "bases_advanced",
        "bases_advanced_on_balls_in_play",
        "surplus_bases_advanced_on_balls_in_play",
        "outs_on_extra_base_advance_attempts",
        "pitches",
        "swings",
        "swings_with_contact",
        "strikes",
        "strikes_called",
        "strikes_swinging",
        "strikes_foul",
        "strikes_foul_tip",
        "strikes_in_play",
        "strikes_unknown",
        "balls",
        "balls_called",
        "balls_intentional",
        "balls_automatic",
        "unknown_pitches",
        "pitchouts",
        "pitcher_pickoff_attempts",
        "catcher_pickoff_attempts",
        "pitches_blocked_by_catcher",
        "pitches_with_runners_going",
        "passed_balls",
        "wild_pitches",
        "balks",
        "left_on_base",
        "left_on_base_with_two_outs"
    ]) }}
{% endmacro %}

{% macro event_level_pitching_stats() %}
    {% set non_pitching_stats = [
        "plate_appearances",
        "runs_batted_in",
        "plate_appearances_while_on_base",
        "balls_in_play_while_running",
        "balls_in_play_while_on_base",
        "batter_total_bases_while_running",
        "batter_total_bases_while_on_base",
        "times_lead_runner",
        "times_force_on_runner",
        "times_next_base_empty",
    ] %}
    {% set extra_pitching_stats = [
        "batters_faced",
        "outs_recorded",
        "inherited_runners_scored",
        "bequeathed_runners_scored",
        "team_unearned_runs"
    ] %}

    {{ return(extra_pitching_stats + remove_items(event_level_offense_stats(), non_pitching_stats)) }}
{% endmacro %}


{% macro game_level_pitching_stats() %}
    {{ return([
        "games_started",
        "innings_pitched",
        "inherited_runners",
        "bequeathed_runners",
        "games_relieved",
        "games_finished",
        "save_situations_entered",
        "holds",
        "blown_saves",
        "saves_by_rule",
        "save_opportunities",
        "wins",
        "losses",
        "saves",
        "earned_runs",
        "complete_games",
        "shutouts",
        "quality_starts",
        "cheap_wins",
        "tough_losses",
        "no_decisions",
        "no_hitters",
        "perfect_games",
    ]) }}
{% endmacro %}

{% macro remove_items(my_list, values_to_remove) %}
  {% set new_list = [] %}
  {% for item in my_list if item not in values_to_remove %}
    {% do new_list.append(item) %}
  {% endfor %}
  {{ return(new_list) }}
{% endmacro %}