"""Auto-generated by Phase 2 Ibis port. Do not edit by hand."""

from __future__ import annotations

from sqlmesh import model
from sqlmesh.core.macros import MacroEvaluator

from python_models._doc_lookup import doc
from python_models._enum_types import PARK_ID
from python_models.park_factors import batter_pitcher_park_factor

_RATE_STATS = [
    "hits",
    "singles",
    "doubles",
    "triples",
    "reached_on_errors",
    "batting_outs",
]


@model(
    "main_models.calc_park_factor_in_play",
    is_sql=True,
    kind="VIEW",
    columns={
        "park_id": PARK_ID,
        "season": "SMALLINT",
        "league": "VARCHAR",
        "sqrt_sample_size": "DOUBLE",
        **{f"{s}_park_factor": "DOUBLE" for s in _RATE_STATS},
    },
    column_descriptions={
        "park_id": doc("park_id"),
        "season": doc("season"),
        "league": doc("league"),
    },
    grain=["park_id", "season", "league"],
)
def entrypoint(evaluator: MacroEvaluator) -> str:
    del evaluator
    return batter_pitcher_park_factor(
        rate_stats=_RATE_STATS,
        denominator_stat="balls_in_play",
        filter_exp="balls_in_play = 1",
    )
