"""Auto-generated by Phase 2 Ibis port. Do not edit by hand."""

from __future__ import annotations

from sqlmesh import model
from sqlmesh.core.macros import MacroEvaluator

from python_models._doc_lookup import doc
from python_models._enum_types import HAND, PARK_ID
from python_models.park_factors import batter_pitcher_park_factor

_RATE_STATS = [
    "batted_distance_plate",
    "batted_distance_infield",
    "batted_distance_outfield",
    "fielded_by_battery",
    "fielded_by_infielder",
    "fielded_by_outfielder",
    "batted_angle_left",
    "batted_angle_right",
    "batted_angle_middle",
    "batted_location_left_field",
    "batted_location_center_field",
    "batted_location_right_field",
]


@model(
    "main_models.calc_park_factor_hit_location",
    is_sql=True,
    kind="VIEW",
    columns={
        "park_id": PARK_ID,
        "season": "SMALLINT",
        "league": "VARCHAR",
        "batter_hand": HAND,
        "sqrt_sample_size": "DOUBLE",
        **{f"{s}_park_factor": "DOUBLE" for s in _RATE_STATS},
    },
    column_descriptions={
        "park_id": doc("park_id"),
        "season": doc("season"),
        "league": doc("league"),
    },
    grain=["park_id", "season", "league", "batter_hand"],
)
def entrypoint(evaluator: MacroEvaluator) -> str:
    del evaluator
    return batter_pitcher_park_factor(
        rate_stats=_RATE_STATS,
        denominator_stat="plate_appearances",
        filter_exp="batted_location_known = 1 AND hits = 1",
        batter_hand_split=True,
    )
