"""Column-list constants shared across the 9 metrics_* models.

Lifted from bc/macros/_metric_table_body.py — single source of truth
for Phase 2. The macro keeps its own copy until stage G removes it.
"""

from __future__ import annotations

OFFENSE_INT_COLS: list[str] = [
    "plate_appearances",
    "at_bats",
    "hits",
    "singles",
    "doubles",
    "triples",
    "home_runs",
    "total_bases",
    "strikeouts",
    "walks",
    "intentional_walks",
    "hit_by_pitches",
    "sacrifice_hits",
    "sacrifice_flies",
    "reached_on_errors",
    "reached_on_interferences",
    "inside_the_park_home_runs",
    "ground_rule_doubles",
    "infield_hits",
    "on_base_opportunities",
    "on_base_successes",
    "runs_batted_in",
    "grounded_into_double_plays",
    "double_plays",
    "triple_plays",
    "batting_outs",
    "balls_in_play",
    "balls_batted",
    "trajectory_fly_ball",
    "trajectory_ground_ball",
    "trajectory_line_drive",
    "trajectory_pop_up",
    "trajectory_unknown",
    "trajectory_known",
    "trajectory_broad_air_ball",
    "trajectory_broad_ground_ball",
    "trajectory_broad_unknown",
    "trajectory_broad_known",
    "bunts",
    "batted_distance_plate",
    "batted_distance_infield",
    "batted_distance_outfield",
    "batted_distance_unknown",
    "batted_distance_known",
    "fielded_by_battery",
    "fielded_by_infielder",
    "fielded_by_outfielder",
    "fielded_by_known",
    "fielded_by_unknown",
    "batted_angle_left",
    "batted_angle_right",
    "batted_angle_middle",
    "batted_angle_unknown",
    "batted_angle_known",
    "batted_location_plate",
    "batted_location_right_infield",
    "batted_location_middle_infield",
    "batted_location_left_infield",
    "batted_location_left_field",
    "batted_location_center_field",
    "batted_location_right_field",
    "batted_location_unknown",
    "batted_location_known",
    "batted_balls_pulled",
    "batted_balls_opposite_field",
    "runs",
    "times_reached_base",
    "stolen_bases",
    "caught_stealing",
    "picked_off",
    "picked_off_caught_stealing",
    "outs_on_basepaths",
    "unforced_outs_on_basepaths",
    "outs_avoided_on_errors",
    "advances_on_wild_pitches",
    "advances_on_passed_balls",
    "advances_on_balks",
    "advances_on_unspecified_plays",
    "advances_on_defensive_indifference",
    "advances_on_errors",
    "plate_appearances_while_on_base",
    "balls_in_play_while_running",
    "balls_in_play_while_on_base",
    "batter_total_bases_while_running",
    "batter_total_bases_while_on_base",
    "extra_base_advance_attempts",
    "bases_advanced",
    "bases_advanced_on_balls_in_play",
    "surplus_bases_advanced_on_balls_in_play",
    "outs_on_extra_base_advance_attempts",
    "pitches",
    "swings",
    "swings_with_contact",
    "strikes",
    "strikes_called",
    "strikes_swinging",
    "strikes_foul",
    "strikes_foul_tip",
    "strikes_in_play",
    "strikes_unknown",
    "balls",
    "balls_called",
    "balls_intentional",
    "balls_automatic",
    "unknown_pitches",
    "pitchouts",
    "pitcher_pickoff_attempts",
    "catcher_pickoff_attempts",
    "pitches_blocked_by_catcher",
    "pitches_with_runners_going",
    "passed_balls",
    "wild_pitches",
    "balks",
    "left_on_base",
    "left_on_base_with_two_outs",
    "stolen_bases_second",
    "stolen_bases_third",
    "stolen_bases_home",
    "caught_stealing_second",
    "caught_stealing_third",
    "caught_stealing_home",
    "stolen_base_opportunities",
    "stolen_base_opportunities_second",
    "stolen_base_opportunities_third",
    "stolen_base_opportunities_home",
    "picked_off_first",
    "picked_off_second",
    "picked_off_third",
    "times_force_on_runner",
    "times_lead_runner",
    "times_next_base_empty",
    "extra_base_chances",
    "extra_bases_taken",
]

PITCHING_INT_COLS: list[str] = [
    "wins",
    "losses",
    "saves",
    "earned_runs",
    "batters_faced",
    "outs_recorded",
    "inherited_runners_scored",
    "bequeathed_runners_scored",
    "team_unearned_runs",
    "at_bats",
    "hits",
    "singles",
    "doubles",
    "triples",
    "home_runs",
    "total_bases",
    "strikeouts",
    "walks",
    "intentional_walks",
    "hit_by_pitches",
    "sacrifice_hits",
    "sacrifice_flies",
    "reached_on_errors",
    "reached_on_interferences",
    "inside_the_park_home_runs",
    "ground_rule_doubles",
    "infield_hits",
    "on_base_opportunities",
    "on_base_successes",
    "grounded_into_double_plays",
    "double_plays",
    "triple_plays",
    "batting_outs",
    "balls_in_play",
    "balls_batted",
    "trajectory_fly_ball",
    "trajectory_ground_ball",
    "trajectory_line_drive",
    "trajectory_pop_up",
    "trajectory_unknown",
    "trajectory_known",
    "trajectory_broad_air_ball",
    "trajectory_broad_ground_ball",
    "trajectory_broad_unknown",
    "trajectory_broad_known",
    "bunts",
    "batted_distance_plate",
    "batted_distance_infield",
    "batted_distance_outfield",
    "batted_distance_unknown",
    "batted_distance_known",
    "fielded_by_battery",
    "fielded_by_infielder",
    "fielded_by_outfielder",
    "fielded_by_known",
    "fielded_by_unknown",
    "batted_angle_left",
    "batted_angle_right",
    "batted_angle_middle",
    "batted_angle_unknown",
    "batted_angle_known",
    "batted_location_plate",
    "batted_location_right_infield",
    "batted_location_middle_infield",
    "batted_location_left_infield",
    "batted_location_left_field",
    "batted_location_center_field",
    "batted_location_right_field",
    "batted_location_unknown",
    "batted_location_known",
    "batted_balls_pulled",
    "batted_balls_opposite_field",
    "runs",
    "times_reached_base",
    "stolen_bases",
    "caught_stealing",
    "picked_off",
    "picked_off_caught_stealing",
    "outs_on_basepaths",
    "unforced_outs_on_basepaths",
    "outs_avoided_on_errors",
    "advances_on_wild_pitches",
    "advances_on_passed_balls",
    "advances_on_balks",
    "advances_on_unspecified_plays",
    "advances_on_defensive_indifference",
    "advances_on_errors",
    "extra_base_advance_attempts",
    "bases_advanced",
    "bases_advanced_on_balls_in_play",
    "surplus_bases_advanced_on_balls_in_play",
    "outs_on_extra_base_advance_attempts",
    "stolen_bases_second",
    "stolen_bases_third",
    "stolen_bases_home",
    "caught_stealing_second",
    "caught_stealing_third",
    "caught_stealing_home",
    "stolen_base_opportunities",
    "stolen_base_opportunities_second",
    "stolen_base_opportunities_third",
    "stolen_base_opportunities_home",
    "picked_off_first",
    "picked_off_second",
    "picked_off_third",
    "pitches",
    "swings",
    "swings_with_contact",
    "strikes",
    "strikes_called",
    "strikes_swinging",
    "strikes_foul",
    "strikes_foul_tip",
    "strikes_in_play",
    "strikes_unknown",
    "balls",
    "balls_called",
    "balls_intentional",
    "balls_automatic",
    "unknown_pitches",
    "pitchouts",
    "pitcher_pickoff_attempts",
    "catcher_pickoff_attempts",
    "pitches_blocked_by_catcher",
    "pitches_with_runners_going",
    "passed_balls",
    "wild_pitches",
    "balks",
    "left_on_base",
    "left_on_base_with_two_outs",
    "games_started",
    "inherited_runners",
    "bequeathed_runners",
    "games_relieved",
    "games_finished",
    "save_situations_entered",
    "holds",
    "blown_saves",
    "saves_by_rule",
    "save_opportunities",
    "complete_games",
    "shutouts",
    "quality_starts",
    "cheap_wins",
    "tough_losses",
    "no_decisions",
    "no_hitters",
    "perfect_games",
    "extra_base_chances",
    "extra_bases_taken",
    "plate_appearances",
]

FIELDING_INT_COLS: list[str] = [
    "games_started",
    "outs_played",
    "putouts",
    "assists",
    "errors",
    "double_plays",
    "triple_plays",
    "plate_appearances_in_field",
    "plate_appearances_in_field_with_ball_in_play",
    "reaching_errors",
    "fielders_choices",
    "assisted_putouts",
    "in_play_putouts",
    "in_play_assists",
    "balls_hit_to",
    "ground_ball_double_plays",
    "passed_balls",
    "stolen_bases",
    "caught_stealing",
    "unknown_putouts_while_fielding",
    "pickoffs",
    "double_plays_started",
    "ground_ball_double_plays_started",
]

INT_COLS: dict[str, list[str]] = {
    "offense": OFFENSE_INT_COLS,
    "pitching": PITCHING_INT_COLS,
    "fielding": FIELDING_INT_COLS,
}

# team_game_start_info columns NOT in the player_*_game_*_stats upstreams.
GAME_COLS: list[str] = [
    "opponent_id",
    "league",
    "opponent_league",
    "division",
    "opponent_division",
    "team_name",
    "opponent_name",
    "starting_pitcher_id",
    "opponent_starting_pitcher_id",
    "team_side",
    "date",
    "start_time",
    "season",
    "doubleheader_status",
    "time_of_day",
    "game_type",
    "bat_first_side",
    "sky",
    "field_condition",
    "precipitation",
    "wind_direction",
    "park_id",
    "temperature_fahrenheit",
    "attendance",
    "wind_speed_mph",
    "use_dh",
    "scorer",
    "scoring_method",
    "source_type",
    "umpire_home_id",
    "umpire_first_id",
    "umpire_second_id",
    "umpire_third_id",
    "umpire_left_id",
    "umpire_right_id",
    "filename",
    "is_regular_season",
    "is_postseason",
    "is_integrated",
    "is_negro_leagues",
    "is_segregated_white",
    "away_franchise_id",
    "home_franchise_id",
    "is_interleague",
    "lineup_map_away",
    "lineup_map_home",
    "fielding_map_away",
    "fielding_map_home",
    "series_id",
    "season_game_number",
    "series_game_number",
    "days_since_last_game",
]

EVENT_MODELS: dict[str, str] = {
    "offense": "main_models.event_offense_stats",
    "pitching": "main_models.event_pitching_stats",
    "fielding": "main_models.event_player_fielding_stats",
}

SEASON_MODELS: dict[str, str] = {
    "offense": "main_models.player_team_season_offense_stats",
    "pitching": "main_models.player_team_season_pitching_stats",
    "fielding": "main_models.player_position_team_season_fielding_stats",
}

# Per-event tables don't carry game-level rollup columns (wins, saves,
# games_started, etc.). Subtract those from INT_COLS when declaring
# Ibis schemas for event_*_stats — otherwise the projection references
# columns DuckDB can't bind.
_PITCHING_GAME_LEVEL_ONLY: frozenset[str] = frozenset({
    "wins", "losses", "saves", "earned_runs", "games_started",
    "inherited_runners", "bequeathed_runners", "games_relieved",
    "games_finished", "save_situations_entered", "holds", "blown_saves",
    "saves_by_rule", "save_opportunities", "complete_games", "shutouts",
    "quality_starts", "cheap_wins", "tough_losses", "no_decisions",
    "no_hitters", "perfect_games",
})

_FIELDING_GAME_LEVEL_ONLY: frozenset[str] = frozenset({"games_started"})

EVENT_INT_COLS: dict[str, list[str]] = {
    "offense": OFFENSE_INT_COLS,
    "pitching": [c for c in PITCHING_INT_COLS if c not in _PITCHING_GAME_LEVEL_ONLY],
    "fielding": [c for c in FIELDING_INT_COLS if c not in _FIELDING_GAME_LEVEL_ONLY],
}
