"""Aggregate offensive statistics over player careers — Phase 2 Ibis port."""

from __future__ import annotations

from sqlmesh import model
from sqlmesh.core.macros import MacroEvaluator

from python_models._doc_lookup import doc
from python_models.metrics.builders import build_metric_sql


@model(
    "main_models.metrics_player_career_offense",
    is_sql=True,
    kind="FULL",
    description="Aggregate offensive statistics and averages over player careers. Regular season only.",
    grain=["player_id"],
    columns={
        "player_id": "VARCHAR",
        "plate_appearances": "INTEGER",
        "at_bats": "INTEGER",
        "hits": "INTEGER",
        "singles": "INTEGER",
        "doubles": "INTEGER",
        "triples": "INTEGER",
        "home_runs": "INTEGER",
        "total_bases": "INTEGER",
        "strikeouts": "INTEGER",
        "walks": "INTEGER",
        "intentional_walks": "INTEGER",
        "hit_by_pitches": "INTEGER",
        "sacrifice_hits": "INTEGER",
        "sacrifice_flies": "INTEGER",
        "reached_on_errors": "INTEGER",
        "reached_on_interferences": "INTEGER",
        "inside_the_park_home_runs": "INTEGER",
        "ground_rule_doubles": "INTEGER",
        "infield_hits": "INTEGER",
        "on_base_opportunities": "INTEGER",
        "on_base_successes": "INTEGER",
        "runs_batted_in": "INTEGER",
        "grounded_into_double_plays": "INTEGER",
        "double_plays": "INTEGER",
        "triple_plays": "INTEGER",
        "batting_outs": "INTEGER",
        "balls_in_play": "INTEGER",
        "balls_batted": "INTEGER",
        "trajectory_fly_ball": "INTEGER",
        "trajectory_ground_ball": "INTEGER",
        "trajectory_line_drive": "INTEGER",
        "trajectory_pop_up": "INTEGER",
        "trajectory_unknown": "INTEGER",
        "trajectory_known": "INTEGER",
        "trajectory_broad_air_ball": "INTEGER",
        "trajectory_broad_ground_ball": "INTEGER",
        "trajectory_broad_unknown": "INTEGER",
        "trajectory_broad_known": "INTEGER",
        "bunts": "INTEGER",
        "batted_distance_plate": "INTEGER",
        "batted_distance_infield": "INTEGER",
        "batted_distance_outfield": "INTEGER",
        "batted_distance_unknown": "INTEGER",
        "batted_distance_known": "INTEGER",
        "fielded_by_battery": "INTEGER",
        "fielded_by_infielder": "INTEGER",
        "fielded_by_outfielder": "INTEGER",
        "fielded_by_known": "INTEGER",
        "fielded_by_unknown": "INTEGER",
        "batted_angle_left": "INTEGER",
        "batted_angle_right": "INTEGER",
        "batted_angle_middle": "INTEGER",
        "batted_angle_unknown": "INTEGER",
        "batted_angle_known": "INTEGER",
        "batted_location_plate": "INTEGER",
        "batted_location_right_infield": "INTEGER",
        "batted_location_middle_infield": "INTEGER",
        "batted_location_left_infield": "INTEGER",
        "batted_location_left_field": "INTEGER",
        "batted_location_center_field": "INTEGER",
        "batted_location_right_field": "INTEGER",
        "batted_location_unknown": "INTEGER",
        "batted_location_known": "INTEGER",
        "batted_balls_pulled": "INTEGER",
        "batted_balls_opposite_field": "INTEGER",
        "runs": "INTEGER",
        "times_reached_base": "INTEGER",
        "stolen_bases": "INTEGER",
        "caught_stealing": "INTEGER",
        "picked_off": "INTEGER",
        "picked_off_caught_stealing": "INTEGER",
        "outs_on_basepaths": "INTEGER",
        "unforced_outs_on_basepaths": "INTEGER",
        "outs_avoided_on_errors": "INTEGER",
        "advances_on_wild_pitches": "INTEGER",
        "advances_on_passed_balls": "INTEGER",
        "advances_on_balks": "INTEGER",
        "advances_on_unspecified_plays": "INTEGER",
        "advances_on_defensive_indifference": "INTEGER",
        "advances_on_errors": "INTEGER",
        "plate_appearances_while_on_base": "INTEGER",
        "balls_in_play_while_running": "INTEGER",
        "balls_in_play_while_on_base": "INTEGER",
        "batter_total_bases_while_running": "INTEGER",
        "batter_total_bases_while_on_base": "INTEGER",
        "extra_base_advance_attempts": "INTEGER",
        "bases_advanced": "INTEGER",
        "bases_advanced_on_balls_in_play": "INTEGER",
        "surplus_bases_advanced_on_balls_in_play": "INTEGER",
        "outs_on_extra_base_advance_attempts": "INTEGER",
        "pitches": "INTEGER",
        "swings": "INTEGER",
        "swings_with_contact": "INTEGER",
        "strikes": "INTEGER",
        "strikes_called": "INTEGER",
        "strikes_swinging": "INTEGER",
        "strikes_foul": "INTEGER",
        "strikes_foul_tip": "INTEGER",
        "strikes_in_play": "INTEGER",
        "strikes_unknown": "INTEGER",
        "balls": "INTEGER",
        "balls_called": "INTEGER",
        "balls_intentional": "INTEGER",
        "balls_automatic": "INTEGER",
        "unknown_pitches": "INTEGER",
        "pitchouts": "INTEGER",
        "pitcher_pickoff_attempts": "INTEGER",
        "catcher_pickoff_attempts": "INTEGER",
        "pitches_blocked_by_catcher": "INTEGER",
        "pitches_with_runners_going": "INTEGER",
        "passed_balls": "INTEGER",
        "wild_pitches": "INTEGER",
        "balks": "INTEGER",
        "left_on_base": "INTEGER",
        "left_on_base_with_two_outs": "INTEGER",
        "stolen_bases_second": "INTEGER",
        "stolen_bases_third": "INTEGER",
        "stolen_bases_home": "INTEGER",
        "caught_stealing_second": "INTEGER",
        "caught_stealing_third": "INTEGER",
        "caught_stealing_home": "INTEGER",
        "stolen_base_opportunities": "INTEGER",
        "stolen_base_opportunities_second": "INTEGER",
        "stolen_base_opportunities_third": "INTEGER",
        "stolen_base_opportunities_home": "INTEGER",
        "picked_off_first": "INTEGER",
        "picked_off_second": "INTEGER",
        "picked_off_third": "INTEGER",
        "times_force_on_runner": "INTEGER",
        "times_lead_runner": "INTEGER",
        "times_next_base_empty": "INTEGER",
        "extra_base_chances": "INTEGER",
        "extra_bases_taken": "INTEGER",
        "batting_average": "DOUBLE",
        "on_base_percentage": "DOUBLE",
        "slugging_percentage": "DOUBLE",
        "on_base_plus_slugging": "DOUBLE",
        "isolated_power": "DOUBLE",
        "secondary_average": "DOUBLE",
        "batting_average_on_balls_in_play": "DOUBLE",
        "home_run_rate": "DOUBLE",
        "walk_rate": "DOUBLE",
        "strikeout_rate": "DOUBLE",
        "stolen_base_percentage": "DOUBLE",
        "event_coverage_rate": "DOUBLE",
        "known_trajectory_rate_outs": "DOUBLE",
        "known_trajectory_rate_hits": "DOUBLE",
        "known_trajectory_rate": "DOUBLE",
        "known_trajectory_broad_rate_outs": "DOUBLE",
        "known_trajectory_broad_rate_hits": "DOUBLE",
        "known_trajectory_broad_rate": "DOUBLE",
        "known_trajectory_out_hit_ratio": "DOUBLE",
        "known_trajectory_broad_out_hit_ratio": "DOUBLE",
        "air_ball_rate_outs": "DOUBLE",
        "ground_ball_rate_outs": "DOUBLE",
        "ground_air_out_ratio": "DOUBLE",
        "air_ball_hit_rate": "DOUBLE",
        "ground_ball_hit_rate": "DOUBLE",
        "ground_air_hit_ratio": "DOUBLE",
        "fly_ball_rate": "DOUBLE",
        "line_drive_rate": "DOUBLE",
        "pop_up_rate": "DOUBLE",
        "ground_ball_rate": "DOUBLE",
        "coverage_weighted_air_ball_batting_average": "DOUBLE",
        "coverage_weighted_ground_ball_batting_average": "DOUBLE",
        "coverage_weighted_fly_ball_batting_average": "DOUBLE",
        "coverage_weighted_line_drive_batting_average": "DOUBLE",
        "coverage_weighted_pop_up_batting_average": "DOUBLE",
        "known_angle_rate_outs": "DOUBLE",
        "known_angle_rate_hits": "DOUBLE",
        "known_angle_rate": "DOUBLE",
        "known_angle_out_hit_ratio": "DOUBLE",
        "angle_left_rate_outs": "DOUBLE",
        "angle_left_rate_hits": "DOUBLE",
        "angle_left_rate": "DOUBLE",
        "coverage_weighted_angle_left_batting_average": "DOUBLE",
        "angle_right_rate_outs": "DOUBLE",
        "angle_right_rate_hits": "DOUBLE",
        "angle_right_rate": "DOUBLE",
        "coverage_weighted_angle_right_batting_average": "DOUBLE",
        "angle_middle_rate_outs": "DOUBLE",
        "angle_middle_rate_hits": "DOUBLE",
        "angle_middle_rate": "DOUBLE",
        "coverage_weighted_angle_middle_batting_average": "DOUBLE",
        "pulled_rate_outs": "DOUBLE",
        "pulled_rate_hits": "DOUBLE",
        "pulled_rate": "DOUBLE",
        "coverage_weighted_pulled_batting_average": "DOUBLE",
        "opposite_field_rate_outs": "DOUBLE",
        "opposite_field_rate_hits": "DOUBLE",
        "opposite_field_rate": "DOUBLE",
        "coverage_weighted_opposite_field_batting_average": "DOUBLE",
        "stolen_base_attempt_rate_second": "DOUBLE",
        "stolen_base_attempt_rate_third": "DOUBLE",
        "stolen_base_attempt_rate_home": "DOUBLE",
        "unforced_out_rate": "DOUBLE",
        "pitch_strike_rate": "DOUBLE",
        "pitch_contact_rate": "DOUBLE",
        "pitch_swing_rate": "DOUBLE",
        "pitch_ball_rate": "DOUBLE",
        "pitch_swing_and_miss_rate": "DOUBLE",
        "pitch_foul_rate": "DOUBLE",
        "pitched_called_strike_rate": "DOUBLE",
        "pitch_data_coverage_rate": "DOUBLE",
    },
    column_descriptions={
        "player_id": doc("player_id"),
        "plate_appearances": doc("plate_appearances"),
        "at_bats": doc("at_bats"),
        "hits": doc("hits"),
        "singles": doc("singles"),
        "doubles": doc("doubles"),
        "triples": doc("triples"),
        "home_runs": doc("home_runs"),
        "total_bases": doc("total_bases"),
        "strikeouts": doc("strikeouts"),
        "walks": doc("walks"),
        "intentional_walks": doc("intentional_walks"),
        "hit_by_pitches": doc("hit_by_pitches"),
        "sacrifice_hits": doc("sacrifice_hits"),
        "sacrifice_flies": doc("sacrifice_flies"),
        "reached_on_errors": doc("reached_on_errors"),
        "reached_on_interferences": doc("reached_on_interferences"),
        "inside_the_park_home_runs": doc("inside_the_park_home_runs"),
        "ground_rule_doubles": doc("ground_rule_doubles"),
        "infield_hits": doc("infield_hits"),
        "on_base_opportunities": doc("on_base_opportunities"),
        "on_base_successes": doc("on_base_successes"),
        "runs_batted_in": doc("runs_batted_in"),
        "grounded_into_double_plays": doc("grounded_into_double_plays"),
        "double_plays": doc("double_plays"),
        "triple_plays": doc("triple_plays"),
        "batting_outs": doc("batting_outs"),
        "balls_in_play": doc("balls_in_play"),
        "balls_batted": doc("balls_batted"),
        "trajectory_fly_ball": doc("trajectory_fly_ball"),
        "trajectory_ground_ball": doc("trajectory_ground_ball"),
        "trajectory_line_drive": doc("trajectory_line_drive"),
        "trajectory_pop_up": doc("trajectory_pop_up"),
        "trajectory_unknown": doc("trajectory_unknown"),
        "trajectory_known": doc("trajectory_known"),
        "trajectory_broad_air_ball": doc("trajectory_broad_air_ball"),
        "trajectory_broad_ground_ball": doc("trajectory_broad_ground_ball"),
        "trajectory_broad_unknown": doc("trajectory_broad_unknown"),
        "trajectory_broad_known": doc("trajectory_broad_known"),
        "bunts": doc("bunts"),
        "batted_distance_plate": doc("batted_distance_plate"),
        "batted_distance_infield": doc("batted_distance_infield"),
        "batted_distance_outfield": doc("batted_distance_outfield"),
        "batted_distance_unknown": doc("batted_distance_unknown"),
        "batted_distance_known": doc("batted_distance_known"),
        "fielded_by_battery": doc("fielded_by_battery"),
        "fielded_by_infielder": doc("fielded_by_infielder"),
        "fielded_by_outfielder": doc("fielded_by_outfielder"),
        "fielded_by_known": doc("fielded_by_known"),
        "fielded_by_unknown": doc("fielded_by_unknown"),
        "batted_angle_left": doc("batted_angle_left"),
        "batted_angle_right": doc("batted_angle_right"),
        "batted_angle_middle": doc("batted_angle_middle"),
        "batted_angle_unknown": doc("batted_angle_unknown"),
        "batted_angle_known": doc("batted_angle_known"),
        "batted_location_plate": doc("batted_location_plate"),
        "batted_location_right_infield": doc("batted_location_right_infield"),
        "batted_location_middle_infield": doc("batted_location_middle_infield"),
        "batted_location_left_infield": doc("batted_location_left_infield"),
        "batted_location_left_field": doc("batted_location_left_field"),
        "batted_location_center_field": doc("batted_location_center_field"),
        "batted_location_right_field": doc("batted_location_right_field"),
        "batted_location_unknown": doc("batted_location_unknown"),
        "batted_location_known": doc("batted_location_known"),
        "batted_balls_pulled": doc("batted_balls_pulled"),
        "batted_balls_opposite_field": doc("batted_balls_opposite_field"),
        "runs": doc("runs"),
        "times_reached_base": doc("times_reached_base"),
        "stolen_bases": doc("stolen_bases"),
        "caught_stealing": doc("caught_stealing"),
        "picked_off": doc("picked_off"),
        "picked_off_caught_stealing": doc("picked_off_caught_stealing"),
        "outs_on_basepaths": doc("outs_on_basepaths"),
        "unforced_outs_on_basepaths": doc("unforced_outs_on_basepaths"),
        "outs_avoided_on_errors": doc("outs_avoided_on_errors"),
        "advances_on_wild_pitches": doc("advances_on_wild_pitches"),
        "advances_on_passed_balls": doc("advances_on_passed_balls"),
        "advances_on_balks": doc("advances_on_balks"),
        "advances_on_unspecified_plays": doc("advances_on_unspecified_plays"),
        "advances_on_defensive_indifference": doc("advances_on_defensive_indifference"),
        "advances_on_errors": doc("advances_on_errors"),
        "plate_appearances_while_on_base": doc("plate_appearances_while_on_base"),
        "balls_in_play_while_running": doc("balls_in_play_while_running"),
        "balls_in_play_while_on_base": doc("balls_in_play_while_on_base"),
        "batter_total_bases_while_running": doc("batter_total_bases_while_running"),
        "batter_total_bases_while_on_base": doc("batter_total_bases_while_on_base"),
        "extra_base_advance_attempts": doc("extra_base_advance_attempts"),
        "bases_advanced": doc("bases_advanced"),
        "bases_advanced_on_balls_in_play": doc("bases_advanced_on_balls_in_play"),
        "surplus_bases_advanced_on_balls_in_play": doc(
            "surplus_bases_advanced_on_balls_in_play"
        ),
        "outs_on_extra_base_advance_attempts": doc(
            "outs_on_extra_base_advance_attempts"
        ),
        "pitches": doc("pitches"),
        "swings": doc("swings"),
        "swings_with_contact": doc("swings_with_contact"),
        "strikes": doc("strikes"),
        "strikes_called": doc("strikes_called"),
        "strikes_swinging": doc("strikes_swinging"),
        "strikes_foul": doc("strikes_foul"),
        "strikes_foul_tip": doc("strikes_foul_tip"),
        "strikes_in_play": doc("strikes_in_play"),
        "strikes_unknown": doc("strikes_unknown"),
        "balls": doc("balls"),
        "balls_called": doc("balls_called"),
        "balls_intentional": doc("balls_intentional"),
        "balls_automatic": doc("balls_automatic"),
        "unknown_pitches": doc("unknown_pitches"),
        "pitchouts": doc("pitchouts"),
        "pitcher_pickoff_attempts": doc("pitcher_pickoff_attempts"),
        "catcher_pickoff_attempts": doc("catcher_pickoff_attempts"),
        "pitches_blocked_by_catcher": doc("pitches_blocked_by_catcher"),
        "pitches_with_runners_going": doc("pitches_with_runners_going"),
        "passed_balls": doc("passed_balls"),
        "wild_pitches": doc("wild_pitches"),
        "balks": doc("balks"),
        "left_on_base": doc("left_on_base"),
        "left_on_base_with_two_outs": doc("left_on_base_with_two_outs"),
        "stolen_bases_second": doc("stolen_bases_second"),
        "stolen_bases_third": doc("stolen_bases_third"),
        "stolen_bases_home": doc("stolen_bases_home"),
        "caught_stealing_second": doc("caught_stealing_second"),
        "caught_stealing_third": doc("caught_stealing_third"),
        "caught_stealing_home": doc("caught_stealing_home"),
        "stolen_base_opportunities": doc("stolen_base_opportunities"),
        "stolen_base_opportunities_second": doc("stolen_base_opportunities_second"),
        "stolen_base_opportunities_third": doc("stolen_base_opportunities_third"),
        "stolen_base_opportunities_home": doc("stolen_base_opportunities_home"),
        "picked_off_first": doc("picked_off_first"),
        "picked_off_second": doc("picked_off_second"),
        "picked_off_third": doc("picked_off_third"),
        "times_force_on_runner": doc("times_force_on_runner"),
        "times_lead_runner": doc("times_lead_runner"),
        "times_next_base_empty": doc("times_next_base_empty"),
        "extra_base_chances": doc("extra_base_chances"),
        "extra_bases_taken": doc("extra_bases_taken"),
        "batting_average": doc("batting_average"),
        "on_base_percentage": doc("on_base_percentage"),
        "slugging_percentage": doc("slugging_percentage"),
        "on_base_plus_slugging": doc("on_base_plus_slugging"),
        "isolated_power": doc("isolated_power"),
        "secondary_average": doc("secondary_average"),
        "batting_average_on_balls_in_play": doc("batting_average_on_balls_in_play"),
        "home_run_rate": doc("home_run_rate"),
        "walk_rate": doc("walk_rate"),
        "strikeout_rate": doc("strikeout_rate"),
        "stolen_base_percentage": doc("stolen_base_percentage"),
        "known_trajectory_rate_outs": doc("known_trajectory_rate_outs"),
        "known_trajectory_rate_hits": doc("known_trajectory_rate_hits"),
        "known_trajectory_rate": doc("known_trajectory_rate"),
        "known_trajectory_broad_rate_outs": doc("known_trajectory_broad_rate_outs"),
        "known_trajectory_broad_rate_hits": doc("known_trajectory_broad_rate_hits"),
        "known_trajectory_broad_rate": doc("known_trajectory_broad_rate"),
        "known_trajectory_out_hit_ratio": doc("known_trajectory_out_hit_ratio"),
        "known_trajectory_broad_out_hit_ratio": doc(
            "known_trajectory_broad_out_hit_ratio"
        ),
        "air_ball_rate_outs": doc("air_ball_rate_outs"),
        "ground_ball_rate_outs": doc("ground_ball_rate_outs"),
        "ground_air_out_ratio": doc("ground_air_out_ratio"),
        "air_ball_hit_rate": doc("air_ball_hit_rate"),
        "ground_ball_hit_rate": doc("ground_ball_hit_rate"),
        "ground_air_hit_ratio": doc("ground_air_hit_ratio"),
        "fly_ball_rate": doc("fly_ball_rate"),
        "line_drive_rate": doc("line_drive_rate"),
        "pop_up_rate": doc("pop_up_rate"),
        "ground_ball_rate": doc("ground_ball_rate"),
        "coverage_weighted_air_ball_batting_average": doc(
            "coverage_weighted_air_ball_batting_average"
        ),
        "coverage_weighted_ground_ball_batting_average": doc(
            "coverage_weighted_ground_ball_batting_average"
        ),
        "coverage_weighted_fly_ball_batting_average": doc(
            "coverage_weighted_fly_ball_batting_average"
        ),
        "coverage_weighted_line_drive_batting_average": doc(
            "coverage_weighted_line_drive_batting_average"
        ),
        "coverage_weighted_pop_up_batting_average": doc(
            "coverage_weighted_pop_up_batting_average"
        ),
        "known_angle_rate_outs": doc("known_angle_rate_outs"),
        "known_angle_rate_hits": doc("known_angle_rate_hits"),
        "known_angle_rate": doc("known_angle_rate"),
        "known_angle_out_hit_ratio": doc("known_angle_out_hit_ratio"),
        "angle_left_rate_outs": doc("angle_left_rate_outs"),
        "angle_left_rate_hits": doc("angle_left_rate_hits"),
        "angle_left_rate": doc("angle_left_rate"),
        "coverage_weighted_angle_left_batting_average": doc(
            "coverage_weighted_angle_left_batting_average"
        ),
        "angle_right_rate_outs": doc("angle_right_rate_outs"),
        "angle_right_rate_hits": doc("angle_right_rate_hits"),
        "angle_right_rate": doc("angle_right_rate"),
        "coverage_weighted_angle_right_batting_average": doc(
            "coverage_weighted_angle_right_batting_average"
        ),
        "angle_middle_rate_outs": doc("angle_middle_rate_outs"),
        "angle_middle_rate_hits": doc("angle_middle_rate_hits"),
        "angle_middle_rate": doc("angle_middle_rate"),
        "coverage_weighted_angle_middle_batting_average": doc(
            "coverage_weighted_angle_middle_batting_average"
        ),
        "pulled_rate_outs": doc("pulled_rate_outs"),
        "pulled_rate_hits": doc("pulled_rate_hits"),
        "pulled_rate": doc("pulled_rate"),
        "coverage_weighted_pulled_batting_average": doc(
            "coverage_weighted_pulled_batting_average"
        ),
        "opposite_field_rate_outs": doc("opposite_field_rate_outs"),
        "opposite_field_rate_hits": doc("opposite_field_rate_hits"),
        "opposite_field_rate": doc("opposite_field_rate"),
        "coverage_weighted_opposite_field_batting_average": doc(
            "coverage_weighted_opposite_field_batting_average"
        ),
        "stolen_base_attempt_rate_second": doc("stolen_base_attempt_rate_second"),
        "stolen_base_attempt_rate_third": doc("stolen_base_attempt_rate_third"),
        "stolen_base_attempt_rate_home": doc("stolen_base_attempt_rate_home"),
        "unforced_out_rate": doc("unforced_out_rate"),
        "pitch_strike_rate": doc("pitch_strike_rate"),
        "pitch_contact_rate": doc("pitch_contact_rate"),
        "pitch_swing_rate": doc("pitch_swing_rate"),
        "pitch_ball_rate": doc("pitch_ball_rate"),
        "pitch_swing_and_miss_rate": doc("pitch_swing_and_miss_rate"),
        "pitch_foul_rate": doc("pitch_foul_rate"),
        "pitched_called_strike_rate": doc("pitched_called_strike_rate"),
        "pitch_data_coverage_rate": doc("pitch_data_coverage_rate"),
    },
    physical_properties={
        "download_parquet": "https://data.baseball.computer/dbt/main_models_metrics_player_career_offense.parquet",
    },
)
def entrypoint(evaluator: MacroEvaluator) -> str:
    del evaluator
    return build_metric_sql("offense", ["player_id"])
